name: Criar tabela postgress

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
  create-table:
    environment: Teste
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Actualiza Ubuntu e instala pgsql
        run: |
          sudo apt update
          sudo apt -y install postgresql-client
          
      # Create table
      - name: Cria a tabela no postgress
        run: |
          PGPASSWORD=${{ secrets.PGPASSWORD }} psql -U ${{ secrets.USER_PG }} -h {{ secrets.CONNECTION }} -d {{ secrets.DATABASE }} -i tabela.sql
